# Generated by Django 4.1.3 on 2023-04-16 06:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Creature must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Skill must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'spell must be greater than 1 character')])),
            ],
        ),
        migrations.CreateModel(
            name='character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Skill must be greater than 1 character')])),
                ('CharacterName', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Skill must be greater than 1 character')])),
                ('virtue', models.IntegerField(default=50)),
                ('rep', models.IntegerField(default=50)),
                ('xp', models.IntegerField(default=0)),
                ('creatureType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ros.creature')),
            ],
        ),
    ]
